import os
import requests
import sys

# Configuration
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
REPO = os.environ.get("GITHUB_REPOSITORY")
PR_NUMBER = os.environ.get("PR_NUMBER")
MIN_LENGTH = 50  # Characters for description
MIN_TITLE_LENGTH = 10 # Characters for title

def get_pr_details():
    """Fetches details of the Pull Request."""
    url = f"https://api.github.com/repos/{REPO}/pulls/{PR_NUMBER}"
    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        print(f"Error fetching PR details: {response.status_code} {response.text}")
        sys.exit(1)
    return response.json()

def get_pr_diff():
    """Fetches the diff of the Pull Request."""
    url = f"https://api.github.com/repos/{REPO}/pulls/{PR_NUMBER}"
    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3.diff"
    }
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        print(f"Error fetching PR diff: {response.status_code} {response.text}")
        sys.exit(1)
    return response.text

def generate_pr_content(diff, current_title, current_body):
    """Generates a PR title and description using Gemini API."""
    url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent"
    headers = {
        "x-goog-api-key": GEMINI_API_KEY,
        "Content-Type": "application/json"
    }
    
    # Truncate diff
    truncated_diff = diff[:100000]
    if len(diff) > 100000:
        truncated_diff += "\n... (Diff truncated)"

    # Determine if we need to generate a description
    needs_description = len(current_body.strip()) < MIN_LENGTH
    
    prompt = f"""
    You are an expert software engineer and code reviewer. 
    Analyze the following git diff and the current Pull Request title.
    
    Current Title: "{current_title}"
    
    Task:
    1. **Evaluate Title**: Check if the current title is too short (under 10 chars), generic (like "update", "fix", "changes"), or does not accurately reflect the changes in the diff. 
       - If it is bad, generate a concise, descriptive title (e.g., "feat: add user login", "fix: resolve null pointer in auth").
       - If the current title is good and descriptive, return `null` for the title.
    
    2. **Generate Description**: 
       - If the boolean flag `needs_description` is true, generate a comprehensive markdown description (Summary, Key Changes, Technical Details).
       - If `needs_description` is false, return `null` for the description.
    
    Input Flags:
    - needs_description: {str(needs_description).lower()}
    
    Git Diff:
    {truncated_diff}
    
    **IMPORTANT**: Output ONLY a valid JSON object with the following structure:
    {{
        "new_title": "string or null",
        "description": "string or null"
    }}
    """
    
    payload = {
        "contents": [{
            "parts": [{"text": prompt}]
        }]
    }
    
    response = requests.post(url, headers=headers, json=payload)
    if response.status_code != 200:
        print(f"Error calling Gemini API: {response.status_code} {response.text}")
        return None
        
    try:
        result = response.json()
        if 'candidates' not in result or not result['candidates']:
            print("No candidates returned by Gemini.")
            print(f"Full response: {result}")
            return None
            
        candidate = result['candidates'][0]
        if 'content' not in candidate:
            print("No content in candidate (possibly blocked).")
            print(f"Full response: {result}")
            return None
            
        content = candidate['content']['parts'][0]['text']
        # Clean up markdown code blocks if present
        content = content.replace("```json", "").replace("```", "").strip()
        import json
        return json.loads(content)
    except (KeyError, IndexError, TypeError, json.JSONDecodeError) as e:
        print(f"Error parsing Gemini response: {e}")
        print(f"Response: {result}")
        return None

def update_pr(updates):
    """Updates the Pull Request with provided changes."""
    url = f"https://api.github.com/repos/{REPO}/pulls/{PR_NUMBER}"
    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }
    
    data = {}
    if updates.get('new_title'):
        data['title'] = updates['new_title']
    if updates.get('description'):
        data['body'] = updates['description'] + "\n\n---\n*Auto-generated by Gemini AI*"
        
    if not data:
        print("No updates to apply.")
        return

    response = requests.patch(url, headers=headers, json=data)
    if response.status_code != 200:
        print(f"Error updating PR: {response.status_code} {response.text}")
        sys.exit(1)
    print(f"Successfully updated PR: {list(data.keys())}")

def main():
    if not GEMINI_API_KEY:
        print("GEMINI_API_KEY is not set. Skipping.")
        sys.exit(0)

    print(f"Processing PR #{PR_NUMBER} in {REPO}")
    
    pr = get_pr_details()
    current_body = pr.get('body', '') or ""
    current_title = pr.get('title', '')
    
    print("Fetching diff...")
    diff = get_pr_diff()
    
    if not diff.strip():
        print("Diff is empty. Skipping.")
        return

    print("Analyzing PR with Gemini...")
    generated_content = generate_pr_content(diff, current_title, current_body)
    
    if generated_content:
        update_pr(generated_content)
    else:
        print("Failed to generate content.")

if __name__ == "__main__":
    main()
