import { describe, it, expect, vi, beforeEach } from 'vitest';

/**
 * UpdateResolveConfigFile.service.ts
 *
 * Reads /etc/resolv.conf, replaces or appends nameserver lines, and writes back.
 * Uses a static writeChain promise to serialize concurrent writes.
 *
 * We mock `fs/promises` to avoid touching the real filesystem.
 */

const mockReadFile = vi.fn();
const mockWriteFile = vi.fn().mockResolvedValue(undefined);

vi.mock('fs/promises', () => ({
  default: { readFile: mockReadFile, writeFile: mockWriteFile },
}));

describe('UpdateResolveConfigFileService', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    // Reset the static write chain between tests
    vi.resetModules();
  });

  it('replaces existing nameserver line with the new IP', async () => {
    mockReadFile.mockResolvedValue('nameserver 8.8.8.8\nsearch example.com\n');

    const { default: UpdateResolveConfigFileService } = await import('@dhcp/src/service/UpdateResolveConfigFile.service');
    await new UpdateResolveConfigFileService('192.168.1.100').updateConfig();

    expect(mockWriteFile).toHaveBeenCalledWith(
      '/etc/resolv.conf',
      'nameserver 192.168.1.100\nsearch 192.168.1.100\n',
      'utf-8'
    );
  });

  it('appends nameserver when none exists', async () => {
    mockReadFile.mockResolvedValue('# Generated by NexoralDNS\nsearch example.com\n');

    const { default: UpdateResolveConfigFileService } = await import('@dhcp/src/service/UpdateResolveConfigFile.service');
    await new UpdateResolveConfigFileService('10.0.0.5').updateConfig();

    const written = mockWriteFile.mock.calls[0][1] as string;
    expect(written).toContain('nameserver 10.0.0.5');
    expect(written).toContain('search 10.0.0.5');
  });

  it('replaces multiple nameserver lines', async () => {
    mockReadFile.mockResolvedValue('nameserver 8.8.8.8\nnameserver 8.8.4.4\n');

    const { default: UpdateResolveConfigFileService } = await import('@dhcp/src/service/UpdateResolveConfigFile.service');
    await new UpdateResolveConfigFileService('172.16.0.1').updateConfig();

    const written = mockWriteFile.mock.calls[0][1] as string;
    // All nameserver lines should be replaced
    expect(written).not.toContain('8.8.8.8');
    expect(written).not.toContain('8.8.4.4');
    expect(written).toContain('nameserver 172.16.0.1');
  });

  it('falls back to 127.0.0.53 when no IP is provided', async () => {
    mockReadFile.mockResolvedValue('nameserver 8.8.8.8\n');

    const { default: UpdateResolveConfigFileService } = await import('@dhcp/src/service/UpdateResolveConfigFile.service');
    await new UpdateResolveConfigFileService().updateConfig();

    expect(mockWriteFile).toHaveBeenCalledWith(
      '/etc/resolv.conf',
      'nameserver 127.0.0.53\n',
      'utf-8'
    );
  });

  it('falls back to 127.0.0.53 when IP is empty string', async () => {
    mockReadFile.mockResolvedValue('nameserver 8.8.8.8\n');

    const { default: UpdateResolveConfigFileService } = await import('@dhcp/src/service/UpdateResolveConfigFile.service');
    await new UpdateResolveConfigFileService('').updateConfig();

    expect(mockWriteFile).toHaveBeenCalledWith(
      '/etc/resolv.conf',
      'nameserver 127.0.0.53\n',
      'utf-8'
    );
  });

  it('falls back to 127.0.0.53 when IP is whitespace-only', async () => {
    mockReadFile.mockResolvedValue('nameserver 8.8.8.8\n');

    const { default: UpdateResolveConfigFileService } = await import('@dhcp/src/service/UpdateResolveConfigFile.service');
    await new UpdateResolveConfigFileService('   ').updateConfig();

    expect(mockWriteFile).toHaveBeenCalledWith(
      '/etc/resolv.conf',
      'nameserver 127.0.0.53\n',
      'utf-8'
    );
  });

  it('does not modify search line when none exists', async () => {
    mockReadFile.mockResolvedValue('nameserver 8.8.8.8\n');

    const { default: UpdateResolveConfigFileService } = await import('@dhcp/src/service/UpdateResolveConfigFile.service');
    await new UpdateResolveConfigFileService('192.168.1.1').updateConfig();

    const written = mockWriteFile.mock.calls[0][1] as string;
    expect(written).not.toContain('search');
    expect(written).toContain('nameserver 192.168.1.1');
  });

  it('serializes concurrent writes via writeChain', async () => {
    let resolveRead!: () => void;
    const readBlocker = new Promise<void>((r) => { resolveRead = r; });

    // First read blocks, second read returns immediately
    mockReadFile
      .mockImplementationOnce(() => readBlocker.then(() => 'nameserver 8.8.8.8\n'))
      .mockResolvedValueOnce('nameserver 8.8.8.8\n');

    const { default: UpdateResolveConfigFileService } = await import('@dhcp/src/service/UpdateResolveConfigFile.service');

    const svc1 = new UpdateResolveConfigFileService('10.0.0.1');
    const svc2 = new UpdateResolveConfigFileService('10.0.0.2');

    const p1 = svc1.updateConfig();
    const p2 = svc2.updateConfig();

    // Unblock the first read
    resolveRead();
    await Promise.all([p1, p2]);

    // Both writes should have happened (serialized, not interleaved)
    expect(mockWriteFile).toHaveBeenCalledTimes(2);
  });

  it('surfaces errors from file read to the caller', async () => {
    mockReadFile.mockRejectedValue(new Error('EACCES'));

    const { default: UpdateResolveConfigFileService } = await import('@dhcp/src/service/UpdateResolveConfigFile.service');

    // The error is caught inside doUpdate (logged), but updateConfig still resolves
    // because writeChain catches. The caller's promise from doUpdate rejects though.
    await expect(new UpdateResolveConfigFileService('10.0.0.1').updateConfig()).resolves.toBeUndefined();
  });
});
