version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"                 # 👈 exposed to host so nexoraldns can reach it on localhost
    networks:
      - nexoral_network                    # 👈 keep Mongo in bridge network for safety/port isolation

  nexoraldns:
    image: ghcr.io/nexoral/nexoraldns:latest
    container_name: nexoraldns
    restart: always
    network_mode: "host"              # 👈 host mode so it can bind to port 53
    environment:
      - MONGO_URI=mongodb://127.0.0.1:27017/nexoraldns  # 👈 connect via localhost (because host mode)

networks:
  nexoral_network:
    driver: bridge

volumes:
  mongodb_data:
